[package]
name = "steadfast-vulkan-shaders"
version = "0.1.0"
authors = ["Stephen Ribich <stephen@ribich.dev>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.9"
shaderc = "0.7.2"
syn = "1.0.64"
