[package]
name = "steadfast-vulkan"
version = "0.1.0"
authors = ["Stephen Ribich <stephen@ribich.dev>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
libloading = "0.7.0"
int-enum = "0.4"

shared_library = "0.1"
smallvec = "1.6"