[package]
name = "editor"
version = "0.1.0"
authors = ["Stephen Ribich <stephen@ribich.dev>"]
edition = "2018"

[dependencies]
winit = "0.24.0"
steadfast-vulkan = { path = "../steadfast-vulkan", version = "0.1.0" }